# Generated by Django 5.2.1 on 2025-08-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_alter_diseaseprediction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseprediction',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
