# Generated by Django 5.2.1 on 2025-05-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-timestamp',)},
        ),
    ]
